### ISSUE TITLE
Reconnection

### ISSUE THREAD

**Issue by rrsmith** [hapijs/catbox-redis#11]
The error handler set on start kills the client, which means this does not gracefully reconnect when the redis server comes back up. 

Is there any danger in removing this? Or is there some nicer way we could have a graceful reconnect (possibly as an option?)

**Comment by hueniverse** [comment]
@LoicMahieu is the new maintainer.

**Comment by LoicMahieu** [comment]
@SachaCR There is no works scheduled about this and PR is really welcome obviously.
It don't know the best way to handle this. Removing `client.end()` and `self.stop()` can expose us to some memory leak. (?)
I will do some tests for evaluating fixes. Meanwhile PR, comments, etc... are welcome.

**Comment by pierreinglebert** [comment]
Doesn't #21 solve this ?

**Comment by LoicMahieu** [comment]
Yes #21 solves the problem.
