### ISSUE TITLE
Issue while configuring catbox-redis

### ISSUE THREAD

**Issue by Mayankyadav123** [hapijs/catbox-redis#110]
I am developing a hapijs backend and facing issue configuring catbox-redis for tokens.
using gluejs.
I have a manifest.js
import config from "./lib/config";
import { getLogLevel } from "./lib/logging";
import { createConnection } from "./lib/database";
const CatboxRedis = require("@hapi/catbox-redis");

//import Package from "../package.json";
import relish from "relish";

const Relish = relish();

const connection = createConnection(config);
const models =
  process.env.NODE_ENV === "development" || process.env.NODE_ENV === "test"
    ? "./src/models/**/*.js"
    : "./dist/models/**/*.js";

const baseUrl = config.get("web.baseUrl");

const manifest = {
  server: {     // as per hapijs
    cache: [
      {
        name: "redis-cache",
        provider: {
          constructor: CatboxRedis,
          options: {
            partition: "redis_cached_data",
            host: "127.0.0.1",
            port: 6379,
            db: 0,
            tls: {}
          }
        }
      }
    ],
    port: config.get("web.port"),
    host: config.get("web.host"),
    router: {
      stripTrailingSlash: true
    },
    routes: {
      cors: true,
      validate: {
        failAction: Relish.failAction
      }
    }
  },
  register: {
    plugins: [
      {
        plugin: "hapi-auth-jwt2"
      },
      {
        plugin: "hapi-pino",
        options: {
          level: getLogLevel()
        }
      },
      {
        plugin: "hapi-sequelizejs",
        options: [
          {
            name: connection.getDatabaseName(),
            models,
            sequelize: connection,
            sync: true,
            forceSync: false // force sync (drops tables) - default false
          }
        ]
      },
      {
        plugin: "./lib/policies/jwt"
      },
      {
        plugin: "./routes",
        routes: {
          prefix: baseUrl
        }
      }
    ]
  }
};

// register plugins used on development and staging
if (process.env.NODE_ENV !== "production") {
  manifest.register.plugins.push({
    plugin: "@hapi/inert"
  });

  manifest.register.plugins.push({
    plugin: "@hapi/vision"
  });

  manifest.register.plugins.push({
    plugin: "blipp"
  });
}

export { manifest };
======================

FATAL [1577864921092] (144500 on INTMP1E2UX3): Connection is closed.
    Error: Connection is closed.
        at Redis.connectionCloseHandler (C:\Users\1610029\external_api_portal-retail\node_modules\ioredis\built\redis\index.js:305:24)
        at Object.onceWrapper (events.js:281:20)
        at Redis.emit (events.js:193:13)
        at Redis.EventEmitter.emit (domain.js:481:20)
        at processTicksAndRejections (internal/process/task_queues.js:79:9)
[nodemon] app crashed - waiting for file changes before starting...
=======================================================
Please tell me if i am doing any configuration incorrectly or do i need to separately start a local redis instance locally then start my hapijs server??

**Comment by hueniverse** [comment]
Please follow the template instructions and try again.

**Comment by J0NNYZER0** [comment]
I am getting the same error. How come the docs are not straight forward. Like do I register catbox as a module or what? Like this should not be difficult.

**Comment by jshulk** [comment]
Issue is with the official docs, removing "tls" option gets this working.
Reference - https://stackoverflow.com/a/59075822/925214

**Comment by Silur** [comment]
@hueniverse 
it would be nice to fix the example code then, it's weird that in 2021 one has to dig out how to make **broken template instructions** work from the issues.

**Comment by hueniverse** [comment]
@Silur first, maybe find a more productive way to make requests without being so entitled. Second, I don't maintain hapi anymore.

**Comment by Nargonath** [comment]
@Silur code examples are open sourced so if you spot an error you are very welcome to provide a PR for a fix.
