### ISSUE TITLE
Update a key's value (not TTL)

### ISSUE THREAD

**Issue by flippidippi** [hapijs/catbox-redis#114]
* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): community
* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 12.14.1
* *module version*: 5.0.5
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi
* *any other relevant information*: 

#### What problem are you trying to solve?

Currently I don't see a way to "update" a key and keep it's current TTL. I don't see a way to get the current TTL or have it keep whatever is already set. It would be nice to be able to do something like `segment.update(key, value)` that would update the value of the key but keep the TTL the same.

#### Do you have a new or modified API suggestion to solve the problem?
`.update(key, value)` using more of the ioredis capabilities.

**Comment by hueniverse** [comment]
There is no way to do that. It also doesn't make sense to update a cached value without also updating it's ttl. All you can do is set a new, shorter ttl.

**Comment by flippidippi** [comment]
Is there a way to get the current ttl to set a new short ttl?

**Comment by hueniverse** [comment]
You have to get the current value first.

**Comment by flippidippi** [comment]
That doesn't given you the current ttl though correct?

**Comment by hueniverse** [comment]
It should give you the current value and remaining ttl.

**Comment by flippidippi** [comment]
Looks like I needed to add `getDecoratedValue` to the `server.cache` call. Got it thanks!
