### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by achingbrain** [hapijs/catbox-redis#23]
The ability to select a database to use for caching was [added to this module a few months ago](https://github.com/hapijs/catbox-redis/commit/cab7ef11d540a3a0a6a4f229a3492de2448f8f8e).

The latest version on npm is a bit older than this and doesn't have this feature - is there any chance of a new release in the near future?

**Comment by ludoblues** [comment]
@LoicMahieu The [Auto reconnect feature](https://github.com/hapijs/catbox-redis/pull/21) is not included either in the v1.0.4, maybe we could at least have a beta tag if you still not confident about some points ?

Thanks.

**Comment by LoicMahieu** [comment]
v1.0.5 published. Sorry for the delay
