### ISSUE TITLE
Default partition value mentioned in README is not correct

### ISSUE THREAD

**Issue by robinjmurphy** [hapijs/catbox-redis#24]
Hello,

I'm using catbox-redis but I don't need a `partition` for my cache. The [README](https://github.com/hapijs/catbox-redis/blob/master/README.md#options) says that the `partition` property defaults to empty string. In fact it is formatted as the string `undefined` in all Redis commands.

```js
var Catbox = require('catbox').Client;
var Redis = require('catbox-redis');

var cache = new Catbox(new Redis({
  host: '127.0.0.1',
  port: 6379
}));

cache.start(function (err) {
  if (err) throw err;

  cache.set({
    segment: 'foo',
    id: 'bar'
  }, 'baz', 60000, function (err) {
    if (err) throw err;

    // redis-cli monitor
    // "set" "undefined:foo:bar" "{\"item\":\"baz\",\"stored\":1435517453809,\"ttl\":60000}"
  });
});
```

Setting a value of empty string does have the desired effect, but results in a leading `:` in the key name.

I'm happy to provide a fix to make the code match the README. Would you also like me to drop the leading `:` separator? It seems strange to me to keep it.

Thanks!

**Comment by LoicMahieu** [comment]
Sorry for being late @robinjmurphy 

First of all, the README is not correct. The default partition is not `''` but is `'catbox'`, see https://github.com/hapijs/catbox/blob/master/lib/client.js#L13.
Secondly, it appears you pass an instantiated catbox-redis object to catbox. In this case, options are not set default by catbox.

For a correct behavior:
```js
var cache = new Catbox(Redis, {
  host: '127.0.0.1',
  port: 6379
});
```

Setting a empty string in `partition` will results in a leading `:`. It's a catbox relative issue and must be reported in the specific repository.
