### ISSUE TITLE
Invalidating cache when id is dynamic

### ISSUE THREAD

**Issue by jgrenon** [hapijs/catbox-redis#32]
I have a cache segment storing product-reviews query results. The query include a single product (or more) and other parameters, each of which will affect the result, so they must be included in the cache key for the right result to be produced when the same query is re-executed.
Someone creates a new product-review on a product. Of course, at this point some queries must be invalidated, but I don't have any specific key to drop, because keys are not exclusively based on product id... I don't want to flush the whole cache each time a product review is create nor do I want to wait for all cache entries to expire...
In a previous cache (in-house) I used, I had the concept of drop-key, which was more generic (product id)  than the cache entry key.
Any idea how I could implement this using catbox-redis?

**Comment by LoicMahieu** [comment]
Your question is about [`catbox`](https://github.com/hapijs/catbox) and not `catbox-redis` which is only the redis adapter. I suggest you to move your issue to the catbox repository, or better, create an issue in the repository [`discuss`](https://github.com/hapijs/discuss) of hapi.js, it is dedicated to this kind of question.
But anyway, I don't think there is such concept in catbox.
