### ISSUE TITLE
Allow for partition to be optional

### ISSUE THREAD

**Issue by cejast** [hapijs/catbox-redis#34]
In some cases I don't think a `partition` is necessary - I'm already using `segment` on the `key` object to namespace my keys.

When omitting `partition` from the options it does not default to an empty string as the README suggests (the key instead results in `undefined:segment:key`). Using an empty string would also result in a key prefixed with an unwanted colon (`:segment:key`).

I'd be happy to submit a PR for this if you think this is valid.

**Comment by LoicMahieu** [comment]
`partition` is part of `catbox` and not directly related to this adapter. But anyway the key is resolved by the internal method [`generateKey`](https://github.com/hapijs/catbox-redis/blob/master/lib/index.js#L187) so it would be possible to this module to omit the `partition` when it is undefined.
I look at other adapters and it appears the `partition` is ignored in some of them.
I think it would be a great enhancement as other people already asked for this. I open a PR: #35

**Comment by LoicMahieu** [comment]
Published catbox-redis@1.1.0
