### ISSUE TITLE
Breaking change on 1.0.x releases

### ISSUE THREAD

**Issue by sehod** [hapijs/catbox-redis#42]
Between yesterday and today, the 1.0.x releases stopped supporting Node 0.10. 

I wouldn't expect a patch version bump for a lib to be a breaking platform/API change. Was this intentional? Older systems that depend on ~1.0.x where x < 7 are now breaking.

**Comment by LoicMahieu** [comment]
Hi @sehod 
You are right. It is a mistake, the PR #38 shouldn't be released in a patch. See issue #41 I published version 1.1.1 which supports Node 0.10 again.
But 1.0.x has not been fixed yet, it is in progress.
I am sorry for the inconvenience.

**Comment by LoicMahieu** [comment]
v1.0.10 has just been published and fix the issue.

**Comment by gergoerdosi** [comment]
@LoicMahieu: I think 1.0.9 should be unpublished from npm.

**Comment by sehod** [comment]
Thanks @LoicMahieu
