### ISSUE TITLE
Deprecation warning on failed connect

### ISSUE THREAD

**Issue by jmandzik** [hapijs/catbox-redis#43]
When failing to connect, the version of node-redis this package depends on throws a deprecation warning because `.end()` is called without a flush parameter.

**Comment by j0shua** [comment]
I've created a [PR](https://github.com/hapijs/catbox-redis/pull/47) that simply adds the flush parameter to the client.end() call as recommended on the [node redis docs](https://github.com/NodeRedis/node_redis#clientendflush)

**Comment by LoicMahieu** [comment]
Closed for #47

**Comment by Marsup** [comment]
@LoicMahieu Please complete the milestone here as well.
