### ISSUE TITLE
Using Hashes

### ISSUE THREAD

**Issue by KeKs0r** [hapijs/catbox-redis#48]
Hi,

I was thinking about how catbox behind the curtain stores its values. And its just as key value, the same as in e.g. memcache. And due to the fact that the method name (from hapi) is part of the Key, this adds quite a lot to the memory footprint. 

Would you be open to a PR changing the storage of cache values to a Hash? I know that this is not backwards compatible, but maybe for a new major version?

**Comment by LoicMahieu** [comment]
Hi @KeKs0r 
I am not sure to well understand. This package is responsible to only be a provider for `redis` database for [`catbox`](https://github.com/hapijs/catbox) library.
Are you sure that your issue should not be addressed to the catbox repository ?
Thanks

**Comment by KeKs0r** [comment]
Hi @LoicMahieu 

Yes, since it is changing the implementation how catbox-redis is storing its values in redis. For catbox nothing would change.

To illustrate this a little better: Instead of using SET and GET (to store and retrieve values from redis)
Lets assume we have the following method to be cached:
``javascript
server.method('getUser', (userId, cb) => {
   db.select('user').where({id:user}).exec(cb);
});
```
currently this would result in being stored in redis (with userId = 5) under the key `#getUser%3A5`. 
I would like to store it as a HASH (http://redis.io/commands#hash) so that the key would only be: `#getUser' for the method and then the combination between arguments and values as hashvalues:

```
{
  5: {name: 'example user', id:5}
}
```

This lowers the memory footprint since the keys are getting shorter. 
See the capital `Using hashes to abstract a very memory efficient plain key-value store on top of Redis` at http://redis.io/topics/memory-optimization

I hope this is a little clearer now.

**Comment by LoicMahieu** [comment]
Hi @KeKs0r 

Thanks for your explanation. It seems to be what @mark-bradshaw tried to accomplish in #17 .
I am obviously open to performance optimization, even if it breaks the storage. It would be awesome if we can prove the performance gain with benchmarks!

**Comment by KeKs0r** [comment]
It is indeed the same idea as #17. So I guess we can close this issue and continue the discussion there.

I don't think we need a particular benchmark since its not improving actual performance but memory footprint. And I guess there are some already out there. (I remember a talk about redis where someone mentioned memory savings above 30% with this approach. Also it is what the official redis documentation recommends for optimizing the memory footprint.
