### ISSUE TITLE
Connecting over SSL

### ISSUE THREAD

**Issue by franzip** [hapijs/catbox-redis#50]
Hi,

I am using Microsoft Azure Redis Cache which comes with SSL enabled by default.
Is there a way to pass a tls config object to `redis.createClient()` ?

**Comment by mtharrison** [comment]
Relevant: https://github.com/NodeRedis/node_redis/issues/650

**Comment by carlosfaria94** [comment]
The solution is to enable non-SSL port in Azure

https://azure.microsoft.com/en-us/documentation/articles/cache-nodejs-get-started/

**Comment by kanongil** [comment]
A shift to [ioredis](https://github.com/hapijs/catbox-redis/pull/539) would make SSL/TLS a simple config option.

**Comment by LoicMahieu** [comment]
catbox-redis@3.0.1 is out. We switch to `ioredis` for communication with Redis.
Please take a look and re-open the issue if you think the problem is not solved.
Thanks.
