### ISSUE TITLE
catbox-redis cannot retrieve value of 0 from cache.

### ISSUE THREAD

**Issue by claaslange** [hapijs/catbox-redis#59]
#### What are you trying to achieve or the steps to reproduce?

When I store an integer of value 0 in catbox, I want to be able to retrieve it later without any problems.

#### What was the result you received?

When I try to get the value from `catbox-redis` I receive an error stating `Error: Incorrect envelope structure`.

#### What did you expect?

I expect to get back my value of 0.

#### Context

This happens because of the envelope check in https://github.com/hapijs/catbox-redis/blob/master/lib/index.js#L133. Since `!0 === true` is `true` the error condition is triggered, although both `envelope.item` and `envelope.stored` are set.

* *node version*: 6
* *catbox-redis version*: 2.0.2
* *os*: ubuntu
* *any other relevant information*: Getting the value via `redis-cli` shows the following: `"{\"item\":0,\"stored\":1485425585361,\"ttl\":6}"`

**Comment by EgoAleSum** [comment]
This should be fixed in 4.0.0

**Comment by marcuspoehls** [comment]
@claaslange Hey Claas, this is fixed in `catbox-redis` v4. We’ve added [a test for that](https://github.com/hapijs/catbox-redis/blob/68cd76de17d6fcb074d7163f697fb49c22db550e/test/index.js#L786) to make sure this does not break in future releases :)

Have fun!

**Comment by steevhise** [comment]
Can this be backported to hapi 16?
