### ISSUE TITLE
Suggest switching to ioredis for newer Redis feature support like Clusters

### ISSUE THREAD

**Issue by abritinthebay** [hapijs/catbox-redis#60]
The current Redis module is barely updated when it comes to features. Specifically it's completely missing support for a major feature: Clusters.

It also has been missing that feature for _years_. 

The other major Redis client- https://github.com/luin/ioredis-  is basically drop-in as a replacement and supports clusters.

Thoughts about switching? I'd open a PR but want to know if it would even be accepted.

**Comment by devinivy** [comment]
Check out #53!

**Comment by abritinthebay** [comment]
![Oooooooo](https://media.giphy.com/media/nVXzt7FSJlX7W/giphy.gif)

ok, closing then as it's already in progress 😅
