### ISSUE TITLE
Support for separate read and write redis servers.

### ISSUE THREAD

**Issue by abritinthebay** [hapijs/catbox-redis#61]
This would involve creating two connections internally. Using one for reads and one for writes.

This is very useful when dealing with read replicas for scaling purposes.

Suggested example config would be:

```
config: {
	host,
	port,
	// etc
	read : {
		host,
		port,
		// etc
	},
	readClient
}
```

Where `read` is either an object (or, optionally, a `redis:.//` connection url?) and `readClient` is the read replica equivalent of `client`. That way it only uses the read config if present and is backward compatible with the current structure.

Working on supporting this for my company's site so if you're interested a PR will likely be on the way ;)

**Comment by niklasR** [comment]
Hi, @abritinthebay just wondering if you've got that working anywhere? Would be interested in exactly this!

**Comment by abritinthebay** [comment]
I got it working with ioredis locally/on work test servers but nothing I can (legally/ethically) share. We also transitioned away from Redis (too slow for our use case!) so it’s not current.

That said: wasn’t too hard to get working.

**Comment by marcuspoehls** [comment]
I’ll have a look at this issue next week. Will keep you in the loop

**Comment by marcuspoehls** [comment]
I'm hesitant to add this functionality to `catbox-redis`. I guess a custom `client` is suited best for this.

Will close it here. If I miss something, please comment/reopen :)
Thank you!
