### ISSUE TITLE
Sentinel Support

### ISSUE THREAD

**Issue by SimonSchick** [hapijs/catbox-redis#65]
We recently [forked](https://github.com/WatchBeam/catbox-redis) this repo in order to add native sentinel config support to it.

I'd like to pull request this, but adding a full sentinel integration tests would require me to add a full sentinel config and another 2 redis instances.

Would it be sufficient to mock out `ioredis` and simply check if it was called with the right arguments?

**Comment by LoicMahieu** [comment]
Hi @SimonSchick 
Nice work! Indeed, full integration test with a sentinel redis setup would be difficult to reproduce in travis.
Mocking `ioredis` looks to be a good alternative as your modifications are really clean.

Go open a PR ! Great work!

**Comment by SimonSchick** [comment]
@LoicMahieu and @hueniverse for review pretty please? 😄

**Comment by hueniverse** [comment]
Sorry but I don't have time for this one.

**Comment by SimonSchick** [comment]
Oh I'm really sorry @hueniverse , I meant to post this on my pull request not on the issue. 😅

**Comment by hueniverse** [comment]
Same thing...
