### ISSUE TITLE
catbox-redis

### ISSUE THREAD

**Issue by love-lulu** [hapijs/catbox-redis#66]
I don't really understand catbox - redis exactly how to connect to, I want the inside of the redis content how to finish, I trouble you to the author, to look at the code, how to obtain the contents of the redis

**Comment by DavidTPate** [comment]
@love-lulu I'm not sure what you need help with, could you please provide some more details?

**Comment by KLVTZ** [comment]
@love-lulu go through the following

https://github.com/hapijs/catbox-redis/blob/master/examples/redis.js

It demonstrates the following:

- How to connect
- How to get content from redis
