### ISSUE TITLE
Server fails to start

### ISSUE THREAD

**Issue by anttiviljami** [hapijs/catbox-redis#68]
When using catbox-redis@3.0.2, the server fails to start, giving this error.

```
/app/user/node_modules/redis-parser/lib/parser.js:326
      throw new TypeError('The options argument contains the property "' + key + '" that is either unkown or of a wrong type')
      ^
TypeError: The options argument contains the property "name" that is either unkown or of a wrong type
    at new JavascriptRedisParser (/app/user/node_modules/redis-parser/lib/parser.js:326:13)
    at Redis.exports.initParser (/app/user/node_modules/ioredis/lib/redis/parser.js:20:22)
    at Socket.<anonymous> (/app/user/node_modules/ioredis/lib/redis/event_handler.js:39:10)
    at Socket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1067:10)
```

The exact same configuration works just fine with catbox-redis@3.0.1.

**Comment by LoicMahieu** [comment]
Hi @anttiviljami 
Could you provide a sample config that produce the bug ?
Changes since 3.0.1 are small and should not causes errors https://github.com/hapijs/catbox-redis/compare/v3.0.1...v3.0.2

**Comment by anttiviljami** [comment]
I'm actually using catbox-redis with Hapi.js

Here's the config:

```
new Hapi.Server({
  cache: {
    name: 'redisCache',
    engine: redis,
    url: config.REDIS_URL,
    partition: 'cache',
  }
});
```

**Comment by LoicMahieu** [comment]
I do not know well Hapi. Have you tried removing the `name` key ? Do you encounter the problem with versions prior to `catbox-redis@3.0.2` ?

**Comment by anttiviljami** [comment]
Everything before 3.0.2 seems to work. The name parameter is required for Hapi, unfortunately.

**Comment by anttiviljami** [comment]
It must be that Hapi, when calling the constructor is going into this branch, and not the correct one.

https://github.com/hapijs/catbox-redis/compare/v3.0.1...v3.0.2#diff-6d186b954a58d5bb740f73d84fe39073R47

Could you do a check to see that this.settings.sentinelName also exists to that if structure?

I should report this issue to Hapi as well.

**Comment by kanongil** [comment]
I suspect that Hapi set the `options.name` property to `undefined`. In Hapi / Joi terms that is the similar to `delete options.name`.

However, the redis-parser iterates through all option keys and finds that `typeof undefined !== 'string'`, and throws this error instead of ignoring the option.

The catbox-redis fix should probably be to create a cleaned up copy of the `options` that is handed to redis. This can be done using Hoek:

```js
options = Hoek.applyToDefaults({}, options);
```

**Comment by marcuspoehls** [comment]
@anttiviljami Hey Viljami, is this still an issue for you?

Did you upgrade `catbox-redis` to version 4 or do you need to go with version 3?

**Comment by marcuspoehls** [comment]
@anttiviljami Hi Viljami, just checking in again. Do you have this issue with `catbox-redis` 4?
