### ISSUE TITLE
Azure redis fails

### ISSUE THREAD

**Issue by JasonJJFS** [hapijs/catbox-redis#70]
Cannot save data to Azure Redis, either on secure or non secure ports. Same code works through an open, unproxied connection to a local redis. I notice in the package.json that the ioredis version is 2.x.x. 
An update to 3.x.x solves this issue. Furthermore we cannot seem to connect to Azure Redis port (6380), Again I assume that this is due to the ioredis version that used in catbox-redis as 
Many thanks

**Comment by AdriVanHoudt** [comment]
I made a quick PR since v3 should not break things so let's see if all the tests pass ^^

**Comment by LoicMahieu** [comment]
+ catbox-redis@3.1.0

Thanks @AdriVanHoudt 🎉

**Comment by AdriVanHoudt** [comment]
No problem :D
