### ISSUE TITLE
Azure Redis

### ISSUE THREAD

**Issue by JasonJJFS** [hapijs/catbox-redis#73]
Sorry to reopen this.  We are connecting via SSL. Our config is, I am using a cloned copy locally to debug.
```javascript
cache: [{
        engine: require('C:\\Dev\\JJFSCatboxRedis'),
        name: 'cache',
        host: 'azure ip',
        port: 6380,
        db:8,
        password: 'Azure password',
        tls: {
            ca: fs.readFileSync('config/jj-dev-redis/azure-jj-dev-redis.pem').toString()
        }
    }],
```

With the inclusion of in the lib
```javascript
else if(this.settings.tls) {
        options.tls = this.settings.tls;
        client = Redis.createClient(this.settings.tls, options);
    }
```

What I've noticed is that the redis client object always shows the default settings for PORT and HOST, never the ones set in the Hapi server({}):
```javascript

Redis {
  options: 
     password: '+Azure Password=',
     db: 8,
     tls: { ca: '-----BEGIN CERTIFICATE-----Azure Public Cert==\r\n-----END CERTIFICATE-----' },
     port: 6379,
     host: 'localhost',
     family: 4,
```

**Comment by JasonJJFS** [comment]
Using 

```javascript
client = Redis.createClient(this.settings.tls, this.settings);
```

Produces the correct result

```javascript
 host: 'azure ip',
        port: 6380,
```

**Comment by Elexy** [comment]
I have a PR open to fix Azure hosted Redis.
https://github.com/hapijs/catbox-redis/pull/82

Be sure to keep the connection alive (i.e. PING), Azure Redis will end the connection after 5 minutes.

**Comment by marcuspoehls** [comment]
@JasonJJFS @Elexy I’m picking up `catbox-redis` and will have a look at this issue next week. Will also check the linked PR. More details next week.

**Comment by Elexy** [comment]
Great news. Let me know if you need me to take any action @marcuspoehls

**Comment by JasonJJFS** [comment]
Cool.

**Comment by marcuspoehls** [comment]
Merged
https://github.com/hapijs/catbox-redis/pull/82
