### ISSUE TITLE
Unhandled rejection ReplyError: MOVED 10140 

### ISSUE THREAD

**Issue by RakeshKulangara** [hapijs/catbox-redis#80]
We setup a AWS's Elasticache Redis Cluster (has built-in failover / replication / load balancing, no need to know the server addresses). All we have is a configuration endpoint which will be used for all purposes.

**AWS Documentation**

```Redis (cluster mode enabled) clusters, use the cluster's Configuration Endpoint for all operations. You must use a client that supports Redis Cluster (Redis 3.2). You can still read from individual node endpoints (In the API/CLI these are referred to as Read Endpoints).```

Here are the versions used, we are running node 6.12.2 in production. Here are the catbox versions.

```
    "catbox": "7.1.5",
    "catbox-memory": "2.0.4",
    "catbox-redis": "3.1.1",
```

We are seeing the following error.

```Unhandled rejection ReplyError: MOVED 10140 10.1.0.XX:6379
    at JavascriptRedisParser.returnError (/Users/rakesh/code/node-server/node_modules/ioredis/lib/redis/parser.js:24:25)
    at JavascriptRedisParser.execute (/Users/rakesh/code/node-server/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/Users/rakesh/code/node-server/node_modules/ioredis/lib/redis/event_handler.js:107:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)```

**Comment by SimonSchick** [comment]
I ran into the same problem today.
You need to explicitly pass a custom redis client instance into the server.

Roughly like this:
```typescript
client = new IORedis.Cluster(
    [
        {
            host: host,
            port: port,
        },
    ],
    {
        slotsRefreshTimeout: somethingHigherThan1000I,
        redisOptions: {
            tls: {
                servername: cfg.host
            },
            password: password,
        },
    },
);

new Server({
    cache: [{
        name: 'whatever',
        engine: new CatboxRedis({
            partition: 'whatever2',
            client,
        }),
    }]
})
```

**Comment by SimonSchick** [comment]
@LoicMahieu you should really add an example on how to pass a custom client, it's not really documented but allows passing all sorts of extra options.
You could even considering dropping the hard dependency on `redis` and let people inject their own, making it a peer dep instead so the proxy role of this library goes away.

**Comment by marcuspoehls** [comment]
@SimonSchick Hey Simon, good point. I’ll add that to the documentation. Will keep this issue open until its part of the docs.

**Comment by SimonSchick** [comment]
Actually this might not even solve it, I've had some troubles with the latest version of hapi...

**Comment by SimonSchick** [comment]
`new Server` deep clones all it's options (and therefor the redis client) the only safe way to create a redis cache with a custom client seems to be:

```
    server.cache.provision({
      engine: new CatboxRedis({
        client: redis,
        partition: 'cache',
      }),
      name: 'cache',
    });
```

**Comment by marcuspoehls** [comment]
Thank you for pointing me to this. Will check that as well

**Comment by marcuspoehls** [comment]
@SimonSchick A scenario we’ve seen is that a custom client isn’t connected when passing it as the `client` property in the `catbox-redis` options. Especially the `ioredis` clients needed some extra love to connect properly.

Did you run into those issues?

**Comment by SimonSchick** [comment]
What do you mean?
Post code pls

**Comment by marcuspoehls** [comment]
@SimonSchick supporting Redis clusters in `catbox-redis` requiresa custom `client` instance. The Redis client created in `catbox-redis` does not support cluster mode yet.

I'm currently waiting for the release of `ioredis 4.0`. This will make the custom client handling a lot easier: https://github.com/luin/ioredis/releases

Here's the first draft of the updated readme showing more details on the custom client configuration:
https://github.com/hapijs/catbox-redis/tree/refactor-to-class#use-a-custom-redis-client

Closing this issue here. Please reopen if I missed something

**Comment by lewispham** [comment]
ioredis 4.0 has released already. Does catbox-redis has any plans to support cluster redis?

**Comment by marcuspoehls** [comment]
@lewispham Hi Lewis, Redis cluster support is in planning for `catbox-redis`. There is an open pull request https://github.com/hapijs/catbox-redis/pull/84 that will add this feature.

In case you have time available, you can offer your help in the PR.
Would you be interested in implementing cluster support?

**Comment by lewispham** [comment]
@marcuspoehls Yes I'm interested. But I won't be available until this weekend. So if nobody else is interested then I will take a look at it at that time.

**Comment by SimonSchick** [comment]
I still think we should make a breaking change and ONLY pass the ioredis client into catbox-redis, this drastically reduce this package's code size and avoid having to add wrapper code for redis features.
