### ISSUE TITLE
Add ioredis v4 as dependency.

### ISSUE THREAD

**Issue by SimonSchick** [hapijs/catbox-redis#88]
May I also suggest to remove ioredis as a dependency entirely and have the consumer inject it instead?

**Comment by marcuspoehls** [comment]
Hi Simon, my initial thought is that we can’t make sure the injected redis client supports the commands used by `catbox-redis`. I mean, all clients usually implement the Redis API and there shouldn’t be an issue. However, you never know if that’s true.

In my opinion, keeping ioredis is fine and the user can leverage the `client` option to inject a custom client.

What do you think?

**Comment by SimonSchick** [comment]
Maybe make it a peer dependency instead?

**Comment by marcuspoehls** [comment]
I don't know peer dependencies very well.

@devinivy Devin, can you help me out?

**Comment by SimonSchick** [comment]
@marcuspoehls The main reason why I think we should get rid of redis as a direct dep is that ~20% of the current ctor is just passing through options to the redis constructor.
If you want to do anything _remotely_ complex you will have pass a manually created instance regardless.

**Comment by devinivy** [comment]
The way glue handles this (it relies on hapi) is that it declares hapi as a dependency with as wide a range of acceptable versions as possible.  If the user does not include hapi as a dependency in their project, then glue's dependency will ensure it's available.  If the user _does_ include hapi as a dependency, then `npm install` will have deduped that dependency as long as the versions are compatible.

Using peer dependencies would be pretty much identical, except this case listed above wouldn't be covered,
> If the user does not include hapi as a dependency in their project, then glue's dependency will ensure it's available.

The question of supporting configuration passed as an instance of ioredis is a somewhat separate question in my opinion—it seems like catbox-redis already supports this.  @SimonSchick are you feeling limited by catbox-redis in some way, or are you just hoping to streamline the codebase/API?

**Comment by marcuspoehls** [comment]
For now, I don’t want to remove the `ioredis` dependency. I’m open to any discussion. Please reopen or open a new issue if we should think it through again.

Closing here.
