### ISSUE TITLE
4.2.2 regression — cannot connect to Redis server

### ISSUE THREAD

**Issue by mshick** [hapijs/catbox-redis#92]
I've encountered a regression between 4.2.1 and 4.2.2, where suddenly my servers are unable to connect to my redis instance. This is replicated in two environments, locally (in docker containers) and in my CI environment.

Is there some major change that could account for this? I currently pass a config object like this:

```
    cache: [
      {
        engine: 'catbox-redis',
        url: redis://:pass@redis:6379
      }
    ]
```

**Comment by mshick** [comment]
@marcuspoehls Thanks for addressing. Sorry I didn't do that PR — I just worked around in my own code and had to move on.

**Comment by marcuspoehls** [comment]
@mshick No problem! I hope this issue didn’t cause much trouble for you. Have a great day!
